### ISSUE TITLE
Bad Credentials Timeout

### ISSUE THREAD

**Issue by chisleu** [gjedeer/celery-php#30] opened 2014-08-20 16:53 UTC
Attempting to send a task through RabbitMQ with bad credentials takes 3 seconds to timeout instead of immediately failing.

**Comment by jdufresne** [comment] 2017-05-03 11:46
I'm unable reproduce as described. Attempting to connect to the broker using the php-amplib backend with incorrect credentials fails immediately with the following:

```
PHP Fatal error:  Uncaught PhpAmqpLib\Exception\AMQPProtocolConnectionException: ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile. in celery-php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:661
Stack trace:
#0 [internal function]: PhpAmqpLib\Connection\AbstractConnection->connection_close(Object(PhpAmqpLib\Wire\AMQPReader))
#1 celery-php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(199): call_user_func(Array, Object(PhpAmqpLib\Wire\AMQPReader))
#2 celery-php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AbstractChannel.php(341): PhpAmqpLib\Channel\AbstractChannel->dispatch('10,50', '\x01\x93oACCESS_REFUS...', NULL)
#3 celery-php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php(212): PhpAmqpLib\Channel\AbstractChannel->wait(Array)
#4 celery-php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/Abstra in celery-php/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php on line 661
```

If you're still able to reproduce using the latest release or on the master branch, can you provide a minimal test script along with full details on how to trigger the bug? Thanks.

**Comment by TWC-JosephNicholasYarbrough** [comment] 2017-05-03 15:07
@chisleu here:
I left the company that used PHP and no longer have their work products unfortunately.

We ended up using a simple micro-service to relay messages to celery over HTTP

**Comment by jdufresne** [comment] 2017-05-03 15:31
Thanks for the response. As I can't reproduce the issue, closing.

**Closed by jdufresne** 2017-05-03 15:31 UTC
