### ISSUE TITLE
Infinite wait() when broker dies unexpectedly

### ISSUE THREAD

**Issue by chisleu** [gjedeer/celery-php#33] opened 2014-09-14 00:28 UTC
With either the php or pecl/c driver, when I produce messages very fast, I get stuck in an infinite loop.

I've been at this all day, so my brain is a little fuzzy.

It gets caught in the channel wait() on $ch->close() when you use the php driver. I can't recall the issue with the C driver because I just gave up.

It happens when I use a low delay between calls, but it happens with long delays (although much less commonly.)

Serious issue IMO.

**Comment by jdufresne** [comment] 2017-05-03 11:38
@chisleu Are you still experiencing this? Have you tried the latest versions or master branch, they have fixes to better handle connections resources. Do you have a minimal test script that I can use to reproduce the issue?

**Comment by TWC-JosephNicholasYarbrough** [comment] 2017-05-03 15:04
I left the company that used PHP and no longer have their work products unfortunately.

**Comment by jdufresne** [comment] 2017-05-03 15:32
Thanks for the response. As I can't reproduce the issue, closing.

**Closed by jdufresne** 2017-05-03 15:32 UTC
